//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLIESC_EUREKA_GR08.WSLoginReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSLoginReference.ILoginServicio")]
    public interface ILoginServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServicio/Auth", ReplyAction="http://tempuri.org/ILoginServicio/AuthResponse")]
        bool Auth(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServicio/Auth", ReplyAction="http://tempuri.org/ILoginServicio/AuthResponse")]
        System.Threading.Tasks.Task<bool> AuthAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServicioChannel : CLIESC_EUREKA_GR08.WSLoginReference.ILoginServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServicioClient : System.ServiceModel.ClientBase<CLIESC_EUREKA_GR08.WSLoginReference.ILoginServicio>, CLIESC_EUREKA_GR08.WSLoginReference.ILoginServicio {
        
        public LoginServicioClient() {
        }
        
        public LoginServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Auth(string username, string password) {
            return base.Channel.Auth(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> AuthAsync(string username, string password) {
            return base.Channel.AuthAsync(username, password);
        }
    }
}
