
package ec.edu.monster.ws;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WSMovimiento", targetNamespace = "http://ws.monster.edu.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSMovimiento {


    /**
     * 
     * @param numcuenta
     * @return
     *     returns java.util.List<ec.edu.monster.ws.MovimientoModel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarMovimientos", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.ConsultarMovimientos")
    @ResponseWrapper(localName = "consultarMovimientosResponse", targetNamespace = "http://ws.monster.edu.ec/", className = "ec.edu.monster.ws.ConsultarMovimientosResponse")
    @Action(input = "http://ws.monster.edu.ec/WSMovimiento/consultarMovimientosRequest", output = "http://ws.monster.edu.ec/WSMovimiento/consultarMovimientosResponse")
    public List<MovimientoModel> consultarMovimientos(
        @WebParam(name = "numcuenta", targetNamespace = "")
        String numcuenta);

}
