//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLICON_EUREKA_GR08.CuentaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaModel", Namespace="http://schemas.datacontract.org/2004/07/ws_eureka_bank_soap_dotnet.ec.edu.monster" +
        ".model")]
    [System.SerializableAttribute()]
    public partial class CuentaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChrClieCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChrCuenClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChrCuenCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChrEmplCreaCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChrMoneCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChrSucucodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DecCuenSaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DttCuenFechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntCuenContMovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VchCuenEstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChrClieCodigo {
            get {
                return this.ChrClieCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChrClieCodigoField, value) != true)) {
                    this.ChrClieCodigoField = value;
                    this.RaisePropertyChanged("ChrClieCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChrCuenClave {
            get {
                return this.ChrCuenClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ChrCuenClaveField, value) != true)) {
                    this.ChrCuenClaveField = value;
                    this.RaisePropertyChanged("ChrCuenClave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChrCuenCodigo {
            get {
                return this.ChrCuenCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChrCuenCodigoField, value) != true)) {
                    this.ChrCuenCodigoField = value;
                    this.RaisePropertyChanged("ChrCuenCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChrEmplCreaCuenta {
            get {
                return this.ChrEmplCreaCuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.ChrEmplCreaCuentaField, value) != true)) {
                    this.ChrEmplCreaCuentaField = value;
                    this.RaisePropertyChanged("ChrEmplCreaCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChrMoneCodigo {
            get {
                return this.ChrMoneCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChrMoneCodigoField, value) != true)) {
                    this.ChrMoneCodigoField = value;
                    this.RaisePropertyChanged("ChrMoneCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChrSucucodigo {
            get {
                return this.ChrSucucodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChrSucucodigoField, value) != true)) {
                    this.ChrSucucodigoField = value;
                    this.RaisePropertyChanged("ChrSucucodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DecCuenSaldo {
            get {
                return this.DecCuenSaldoField;
            }
            set {
                if ((this.DecCuenSaldoField.Equals(value) != true)) {
                    this.DecCuenSaldoField = value;
                    this.RaisePropertyChanged("DecCuenSaldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DttCuenFechaCreacion {
            get {
                return this.DttCuenFechaCreacionField;
            }
            set {
                if ((this.DttCuenFechaCreacionField.Equals(value) != true)) {
                    this.DttCuenFechaCreacionField = value;
                    this.RaisePropertyChanged("DttCuenFechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntCuenContMov {
            get {
                return this.IntCuenContMovField;
            }
            set {
                if ((this.IntCuenContMovField.Equals(value) != true)) {
                    this.IntCuenContMovField = value;
                    this.RaisePropertyChanged("IntCuenContMov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VchCuenEstado {
            get {
                return this.VchCuenEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.VchCuenEstadoField, value) != true)) {
                    this.VchCuenEstadoField = value;
                    this.RaisePropertyChanged("VchCuenEstado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CuentaServicio.ICuentaServicio")]
    public interface ICuentaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaServicio/Deposito", ReplyAction="http://tempuri.org/ICuentaServicio/DepositoResponse")]
        bool Deposito(string cuenta, string monto, string tipo, string cuentaDestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaServicio/Deposito", ReplyAction="http://tempuri.org/ICuentaServicio/DepositoResponse")]
        System.Threading.Tasks.Task<bool> DepositoAsync(string cuenta, string monto, string tipo, string cuentaDestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaServicio/ObtenerCuentaPorNumero", ReplyAction="http://tempuri.org/ICuentaServicio/ObtenerCuentaPorNumeroResponse")]
        CLICON_EUREKA_GR08.CuentaServicio.CuentaModel ObtenerCuentaPorNumero(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaServicio/ObtenerCuentaPorNumero", ReplyAction="http://tempuri.org/ICuentaServicio/ObtenerCuentaPorNumeroResponse")]
        System.Threading.Tasks.Task<CLICON_EUREKA_GR08.CuentaServicio.CuentaModel> ObtenerCuentaPorNumeroAsync(string cuenta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICuentaServicioChannel : CLICON_EUREKA_GR08.CuentaServicio.ICuentaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuentaServicioClient : System.ServiceModel.ClientBase<CLICON_EUREKA_GR08.CuentaServicio.ICuentaServicio>, CLICON_EUREKA_GR08.CuentaServicio.ICuentaServicio {
        
        public CuentaServicioClient() {
        }
        
        public CuentaServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuentaServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Deposito(string cuenta, string monto, string tipo, string cuentaDestino) {
            return base.Channel.Deposito(cuenta, monto, tipo, cuentaDestino);
        }
        
        public System.Threading.Tasks.Task<bool> DepositoAsync(string cuenta, string monto, string tipo, string cuentaDestino) {
            return base.Channel.DepositoAsync(cuenta, monto, tipo, cuentaDestino);
        }
        
        public CLICON_EUREKA_GR08.CuentaServicio.CuentaModel ObtenerCuentaPorNumero(string cuenta) {
            return base.Channel.ObtenerCuentaPorNumero(cuenta);
        }
        
        public System.Threading.Tasks.Task<CLICON_EUREKA_GR08.CuentaServicio.CuentaModel> ObtenerCuentaPorNumeroAsync(string cuenta) {
            return base.Channel.ObtenerCuentaPorNumeroAsync(cuenta);
        }
    }
}
