//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLIESCR_EUREKA_GR08.WSLoginReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSLoginReference.ILoginServicio")]
    public interface ILoginServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServicio/Auth", ReplyAction="http://tempuri.org/ILoginServicio/AuthResponse")]
        bool Auth(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServicio/Auth", ReplyAction="http://tempuri.org/ILoginServicio/AuthResponse")]
        System.Threading.Tasks.Task<bool> AuthAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServicioChannel : CLIESCR_EUREKA_GR08.WSLoginReference.ILoginServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServicioClient : System.ServiceModel.ClientBase<CLIESCR_EUREKA_GR08.WSLoginReference.ILoginServicio>, CLIESCR_EUREKA_GR08.WSLoginReference.ILoginServicio {
        
        public LoginServicioClient() {
        }
        
        public LoginServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Auth(string username, string password) {
            return base.Channel.Auth(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> AuthAsync(string username, string password) {
            return base.Channel.AuthAsync(username, password);
        }
    }
}
