
package ec.edu.monster.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WSMovimiento", targetNamespace = "http://ws.monster.edu.ec/", wsdlLocation = "http://localhost:8080/ws_eureka_bank_soap_java/WSMovimiento?wsdl")
public class WSMovimiento_Service
    extends Service
{

    private static final URL WSMOVIMIENTO_WSDL_LOCATION;
    private static final WebServiceException WSMOVIMIENTO_EXCEPTION;
    private static final QName WSMOVIMIENTO_QNAME = new QName("http://ws.monster.edu.ec/", "WSMovimiento");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws_eureka_bank_soap_java/WSMovimiento?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSMOVIMIENTO_WSDL_LOCATION = url;
        WSMOVIMIENTO_EXCEPTION = e;
    }

    public WSMovimiento_Service() {
        super(__getWsdlLocation(), WSMOVIMIENTO_QNAME);
    }

    public WSMovimiento_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSMOVIMIENTO_QNAME, features);
    }

    public WSMovimiento_Service(URL wsdlLocation) {
        super(wsdlLocation, WSMOVIMIENTO_QNAME);
    }

    public WSMovimiento_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSMOVIMIENTO_QNAME, features);
    }

    public WSMovimiento_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSMovimiento_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSMovimiento
     */
    @WebEndpoint(name = "WSMovimientoPort")
    public WSMovimiento getWSMovimientoPort() {
        return super.getPort(new QName("http://ws.monster.edu.ec/", "WSMovimientoPort"), WSMovimiento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSMovimiento
     */
    @WebEndpoint(name = "WSMovimientoPort")
    public WSMovimiento getWSMovimientoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.monster.edu.ec/", "WSMovimientoPort"), WSMovimiento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSMOVIMIENTO_EXCEPTION!= null) {
            throw WSMOVIMIENTO_EXCEPTION;
        }
        return WSMOVIMIENTO_WSDL_LOCATION;
    }

}
