/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.monster.vista;

import ec.edu.monster.service.CuentaService;
import ec.edu.monster.ws.CuentaModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JOHAN
 */
public class RetiroView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RetiroView.class.getName());
    private final CuentaService cuentaService = new CuentaService();
    private CuentaModel cuentaActual = null;
    private String numeroCuentaActual = null;

    /**
     * Creates new form RetiroView
     */
    public RetiroView() {
        initComponents();
        // Agregar listener fuera de la sección generada para que no se elimine al modificar el diseño
        btnBuscarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCuentaActionPerformed(evt);
            }
        });
        
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        
        // Ocultar inicialmente los componentes de retiro
        ocultarComponentesRetiro();
    }
    
    private void ocultarComponentesRetiro() {
        jPanel1.setVisible(false);
        jLabel2.setVisible(false);
        txtMonto.setVisible(false);
        btnRetirar.setVisible(false);
    }
    
    private void mostrarComponentesRetiro() {
        jPanel1.setVisible(true);
        jLabel2.setVisible(true);
        txtMonto.setVisible(true);
        btnRetirar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBuscarCuenta = new javax.swing.JButton();
        txtNumeroCuenta = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblCuentaEncontrada = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSaldoEncontrado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMovimientosEncontrado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnRetirar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese el número de Cuenta");

        btnBuscarCuenta.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBuscarCuenta.setText("Buscar");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCuentaEncontrada.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Cuenta: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("Saldo disponible:");

        lblSaldoEncontrado.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setText("Movimientos");
        jLabel5.setVisible(false);

        lblMovimientosEncontrado.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblMovimientosEncontrado.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblCuentaEncontrada, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblSaldoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCuentaEncontrada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblSaldoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Monto a retirar:");

        txtMonto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnRetirar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRetirar.setText("Retirar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnBuscarCuenta))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnRetirar)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCuenta))
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetirar))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCuentaActionPerformed
        String numeroCuenta = txtNumeroCuenta.getText() != null ? txtNumeroCuenta.getText().trim() : "";
        
        if (numeroCuenta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número de cuenta.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            ocultarComponentesRetiro();
            return;
        }
        
        try {
            CuentaModel cuentaModel = cuentaService.obtenerCuentaPorNumero(numeroCuenta);
            
            if (cuentaModel == null) {
                lblCuentaEncontrada.setText("");
                lblSaldoEncontrado.setText("");
                lblMovimientosEncontrado.setText("");
                ocultarComponentesRetiro();
                JOptionPane.showMessageDialog(this, "No se encontraron datos para la cuenta: " + numeroCuenta, "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            // Guardar la cuenta actual y el número de cuenta
            cuentaActual = cuentaModel;
            numeroCuentaActual = numeroCuenta;
            
            // Establecer el número de cuenta encontrado
            lblCuentaEncontrada.setText(numeroCuenta);
            
            // Establecer el saldo disponible
            lblSaldoEncontrado.setText(String.format("%.2f", cuentaModel.getDecCuenSaldo()));
            
            // Limpiar el campo de movimientos (no se muestra)
            lblMovimientosEncontrado.setText("");
            
            // Limpiar el campo de monto y mostrar los componentes de retiro
            txtMonto.setText("");
            mostrarComponentesRetiro();
            
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error al obtener los datos de la cuenta", e);
            JOptionPane.showMessageDialog(this, "Error al obtener los datos de la cuenta: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            lblCuentaEncontrada.setText("");
            lblSaldoEncontrado.setText("");
            lblMovimientosEncontrado.setText("");
            ocultarComponentesRetiro();
            cuentaActual = null;
            numeroCuentaActual = null;
        }
    }//GEN-LAST:event_btnBuscarCuentaActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        if (cuentaActual == null) {
            JOptionPane.showMessageDialog(this, "Por favor, busque una cuenta primero.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String montoStr = txtMonto.getText() != null ? txtMonto.getText().trim() : "";
        
        if (montoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto a retirar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            double monto = Double.parseDouble(montoStr);
            
            if (monto <= 0) {
                JOptionPane.showMessageDialog(this, "El monto debe ser mayor a cero.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Actualizar el saldo de la cuenta antes de validar para obtener el saldo más reciente
            CuentaModel cuentaActualizada = cuentaService.obtenerCuentaPorNumero(numeroCuentaActual);
            if (cuentaActualizada == null) {
                JOptionPane.showMessageDialog(this, "No se pudo obtener la información actualizada de la cuenta.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            cuentaActual = cuentaActualizada;
            // Actualizar el saldo mostrado en pantalla
            lblSaldoEncontrado.setText(String.format("%.2f", cuentaActualizada.getDecCuenSaldo()));
            
            // Verificar que el saldo sea suficiente
            double saldoActual = cuentaActual.getDecCuenSaldo();
            if (saldoActual < monto) {
                JOptionPane.showMessageDialog(this, 
                    "Saldo insuficiente.\nSaldo disponible: " + String.format("%.2f", saldoActual) + 
                    "\nMonto solicitado: " + String.format("%.2f", monto), 
                    "Error - Fondos Insuficientes", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Realizar el retiro con tipo "RET" y cd null usando el número de cuenta
            boolean exito = cuentaService.realizarDeposito(numeroCuentaActual, montoStr, "RET", null);
            
            if (exito) {
                JOptionPane.showMessageDialog(this, "Retiro realizado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                // Actualizar los datos de la cuenta después del retiro exitoso
                CuentaModel cuentaActualizadaDespues = cuentaService.obtenerCuentaPorNumero(numeroCuentaActual);
                if (cuentaActualizadaDespues != null) {
                    cuentaActual = cuentaActualizadaDespues;
                    // Actualizar el saldo mostrado en pantalla
                    lblSaldoEncontrado.setText(String.format("%.2f", cuentaActualizadaDespues.getDecCuenSaldo()));
                }
                
                // Limpiar el campo de monto
                txtMonto.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Error al realizar el retiro. Verifique que tenga fondos suficientes.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto válido (número).", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error al realizar el retiro", e);
            JOptionPane.showMessageDialog(this, "Error al realizar el retiro: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RetiroView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCuenta;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCuentaEncontrada;
    private javax.swing.JLabel lblMovimientosEncontrado;
    private javax.swing.JLabel lblSaldoEncontrado;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNumeroCuenta;
    // End of variables declaration//GEN-END:variables
}
