//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLIWEB_EUREKA_GR08.MovimientoServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovimientoModel", Namespace="http://schemas.datacontract.org/2004/07/ws_eureka_bank_soap_dotnet.ec.edu.monster" +
        ".model")]
    [System.SerializableAttribute()]
    public partial class MovimientoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTipoMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuentaReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaMovimientoDtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImporteMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCuenta {
            get {
                return this.CodigoCuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoCuentaField, value) != true)) {
                    this.CodigoCuentaField = value;
                    this.RaisePropertyChanged("CodigoCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEmpleado {
            get {
                return this.CodigoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoEmpleadoField, value) != true)) {
                    this.CodigoEmpleadoField = value;
                    this.RaisePropertyChanged("CodigoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTipoMovimiento {
            get {
                return this.CodigoTipoMovimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTipoMovimientoField, value) != true)) {
                    this.CodigoTipoMovimientoField = value;
                    this.RaisePropertyChanged("CodigoTipoMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaReferencia {
            get {
                return this.CuentaReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaReferenciaField, value) != true)) {
                    this.CuentaReferenciaField = value;
                    this.RaisePropertyChanged("CuentaReferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaMovimiento {
            get {
                return this.FechaMovimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaMovimientoField, value) != true)) {
                    this.FechaMovimientoField = value;
                    this.RaisePropertyChanged("FechaMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaMovimientoDt {
            get {
                return this.FechaMovimientoDtField;
            }
            set {
                if ((this.FechaMovimientoDtField.Equals(value) != true)) {
                    this.FechaMovimientoDtField = value;
                    this.RaisePropertyChanged("FechaMovimientoDt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImporteMovimiento {
            get {
                return this.ImporteMovimientoField;
            }
            set {
                if ((this.ImporteMovimientoField.Equals(value) != true)) {
                    this.ImporteMovimientoField = value;
                    this.RaisePropertyChanged("ImporteMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroMovimiento {
            get {
                return this.NumeroMovimientoField;
            }
            set {
                if ((this.NumeroMovimientoField.Equals(value) != true)) {
                    this.NumeroMovimientoField = value;
                    this.RaisePropertyChanged("NumeroMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDescripcion {
            get {
                return this.TipoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDescripcionField, value) != true)) {
                    this.TipoDescripcionField = value;
                    this.RaisePropertyChanged("TipoDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovimientoServicio.IMovimientoServicio")]
    public interface IMovimientoServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientoServicio/Movimientos", ReplyAction="http://tempuri.org/IMovimientoServicio/MovimientosResponse")]
        CLIWEB_EUREKA_GR08.MovimientoServicio.MovimientoModel[] Movimientos(string numcuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimientoServicio/Movimientos", ReplyAction="http://tempuri.org/IMovimientoServicio/MovimientosResponse")]
        System.Threading.Tasks.Task<CLIWEB_EUREKA_GR08.MovimientoServicio.MovimientoModel[]> MovimientosAsync(string numcuenta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovimientoServicioChannel : CLIWEB_EUREKA_GR08.MovimientoServicio.IMovimientoServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovimientoServicioClient : System.ServiceModel.ClientBase<CLIWEB_EUREKA_GR08.MovimientoServicio.IMovimientoServicio>, CLIWEB_EUREKA_GR08.MovimientoServicio.IMovimientoServicio {
        
        public MovimientoServicioClient() {
        }
        
        public MovimientoServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovimientoServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovimientoServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovimientoServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CLIWEB_EUREKA_GR08.MovimientoServicio.MovimientoModel[] Movimientos(string numcuenta) {
            return base.Channel.Movimientos(numcuenta);
        }
        
        public System.Threading.Tasks.Task<CLIWEB_EUREKA_GR08.MovimientoServicio.MovimientoModel[]> MovimientosAsync(string numcuenta) {
            return base.Channel.MovimientosAsync(numcuenta);
        }
    }
}
